// Package output provides functionality for writing generated documentation to files.
package output

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"

	"github.com/neglet30/swag-gen/pkg/swagger"
	"gopkg.in/yaml.v3"
)

// Writer is responsible for writing output files.
type Writer struct {
	outputPath string
}

// NewWriter creates a new output writer.
func NewWriter(outputPath string) *Writer {
	return &Writer{
		outputPath: outputPath,
	}
}

// WriteSwagger writes the Swagger document to a file.
func (w *Writer) WriteSwagger(doc *swagger.SwaggerDoc, filename string, format string) error {
	if doc == nil {
		return fmt.Errorf("swagger document cannot be nil")
	}

	if filename == "" {
		return fmt.Errorf("filename cannot be empty")
	}

	if format == "" {
		format = "json"
	}

	// Create output directory if it doesn't exist
	if err := os.MkdirAll(w.outputPath, 0755); err != nil {
		return fmt.Errorf("failed to create output directory: %w", err)
	}

	// Determine file extension based on format
	ext := ".json"
	if format == "yaml" || format == "yml" {
		ext = ".yaml"
	}

	// Build full file path
	filePath := filepath.Join(w.outputPath, filename+ext)

	// Convert document to bytes
	var data []byte
	var err error

	if format == "yaml" || format == "yml" {
		// Use YAML marshaling
		data, err = yaml.Marshal(doc)
	} else {
		// Use JSON marshaling
		data, err = json.MarshalIndent(doc, "", "  ")
	}

	if err != nil {
		return fmt.Errorf("failed to convert document to %s: %w", format, err)
	}

	// Write to file
	if err := os.WriteFile(filePath, data, 0644); err != nil {
		return fmt.Errorf("failed to write file %s: %w", filePath, err)
	}

	return nil
}

// WriteConfig writes a configuration file.
func (w *Writer) WriteConfig(config *Config, filename string) error {
	if config == nil {
		return fmt.Errorf("config cannot be nil")
	}

	if filename == "" {
		return fmt.Errorf("filename cannot be empty")
	}

	// Create output directory if it doesn't exist
	if err := os.MkdirAll(w.outputPath, 0755); err != nil {
		return fmt.Errorf("failed to create output directory: %w", err)
	}

	// Build full file path
	filePath := filepath.Join(w.outputPath, filename)

	// Convert config to YAML
	data, err := config.ToYAML()
	if err != nil {
		return fmt.Errorf("failed to convert config to YAML: %w", err)
	}

	// Write to file
	if err := os.WriteFile(filePath, data, 0644); err != nil {
		return fmt.Errorf("failed to write file %s: %w", filePath, err)
	}

	return nil
}

// WriteREADME writes a README file.
func (w *Writer) WriteREADME(filename string, title string, description string) error {
	if filename == "" {
		return fmt.Errorf("filename cannot be empty")
	}

	// Create output directory if it doesn't exist
	if err := os.MkdirAll(w.outputPath, 0755); err != nil {
		return fmt.Errorf("failed to create output directory: %w", err)
	}

	// Build full file path
	filePath := filepath.Join(w.outputPath, filename)

	// Generate README content
	content := generateREADME(title, description)

	// Write to file
	if err := os.WriteFile(filePath, []byte(content), 0644); err != nil {
		return fmt.Errorf("failed to write file %s: %w", filePath, err)
	}

	return nil
}

// generateREADME generates README content.
func generateREADME(title string, description string) string {
	if title == "" {
		title = "API Documentation"
	}

	content := fmt.Sprintf("# %s\n\n", title)

	if description != "" {
		content += fmt.Sprintf("%s\n\n", description)
	}

	content += `## Overview

This directory contains the API documentation generated by swag-gen.

## Files

- **swagger.json** - OpenAPI 3.0 specification in JSON format
- **swagger.yaml** - OpenAPI 3.0 specification in YAML format
- **swag-gen.yaml** - Configuration file for swag-gen

## Viewing the Documentation

You can view the API documentation using Swagger UI or ReDoc:

### Swagger UI
- Online: https://swagger.io/tools/swagger-ui/
- Local: Use any HTTP server to serve the files

### ReDoc
- Online: https://redoc.ly/
- Local: Use any HTTP server to serve the files

## Regenerating Documentation

To regenerate the documentation, run:

` + "```bash\n" + `swag-gen init -p ./api -o ./docs
` + "```\n\n" + `
## Configuration

Edit **swag-gen.yaml** to customize the documentation generation:

- **project**: Project information (name, version, description)
- **parser**: Parser configuration (path, exclude patterns)
- **output**: Output configuration (path, format)
- **swagger**: Swagger configuration (title, version, description, basePath)

## Support

For more information, visit: https://github.com/neglet30/swag-gen
`

	return content
}

// GetOutputPath returns the output path.
func (w *Writer) GetOutputPath() string {
	return w.outputPath
}

// FileExists checks if a file exists.
func FileExists(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}

// DirectoryExists checks if a directory exists.
func DirectoryExists(path string) bool {
	info, err := os.Stat(path)
	return err == nil && info.IsDir()
}

// CreateDirectory creates a directory if it doesn't exist.
func CreateDirectory(path string) error {
	if DirectoryExists(path) {
		return nil
	}

	if err := os.MkdirAll(path, 0755); err != nil {
		return fmt.Errorf("failed to create directory %s: %w", path, err)
	}

	return nil
}

// RemoveFile removes a file.
func RemoveFile(path string) error {
	if !FileExists(path) {
		return nil
	}

	if err := os.Remove(path); err != nil {
		return fmt.Errorf("failed to remove file %s: %w", path, err)
	}

	return nil
}
