package config

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/viper"
)

// Config 应用配置
type Config struct {
	Server  ServerConfig  `mapstructure:"server"`
	Project ProjectConfig `mapstructure:"project"`
	Parser  ParserConfig  `mapstructure:"parser"`
	Swagger SwaggerConfig `mapstructure:"swagger"`
	Logger  LoggerConfig  `mapstructure:"logger"`
}

// ServerConfig 服务器配置
type ServerConfig struct {
	Host         string `mapstructure:"host"`
	Port         int    `mapstructure:"port"`
	Env          string `mapstructure:"env"`
	ReadTimeout  int    `mapstructure:"read_timeout"`
	WriteTimeout int    `mapstructure:"write_timeout"`
}

// ProjectConfig 项目配置
type ProjectConfig struct {
	Name        string `mapstructure:"name"`
	Version     string `mapstructure:"version"`
	Description string `mapstructure:"description"`
	BasePath    string `mapstructure:"base_path"`
}

// ParserConfig 解析器配置
type ParserConfig struct {
	EnableCache   bool     `mapstructure:"enable_cache"`
	CacheTTL      int      `mapstructure:"cache_ttl"`
	MaxConcurrent int      `mapstructure:"max_concurrent"`
	ExcludeDirs   []string `mapstructure:"exclude_dirs"`
}

// SwaggerConfig Swagger 配置
type SwaggerConfig struct {
	Version            string `mapstructure:"version"`
	DefaultVersion     string `mapstructure:"default_version"`
	DefaultTitle       string `mapstructure:"default_title"`
	DefaultDescription string `mapstructure:"default_description"`
}

// LoggerConfig 日志配置
type LoggerConfig struct {
	Level  string `mapstructure:"level"`
	Format string `mapstructure:"format"`
	Output string `mapstructure:"output"`
}

// Load 加载配置
func Load(configPath string) (*Config, error) {
	v := viper.New()

	// 设置配置文件
	if configPath != "" {
		v.SetConfigFile(configPath)
	} else {
		// 查找配置文件
		v.SetConfigName("config")
		v.SetConfigType("yaml")
		v.AddConfigPath(".")
		v.AddConfigPath("./config")
	}

	// 设置默认值
	setDefaults(v)

	// 读取配置文件
	if err := v.ReadInConfig(); err != nil {
		if _, ok := err.(viper.ConfigFileNotFoundError); !ok {
			return nil, fmt.Errorf("读取配置文件失败: %w", err)
		}
		// 配置文件不存在，使用默认值
	}

	// 绑定环境变量
	v.BindEnv("server.port", "SWAG_GEN_PORT")
	v.BindEnv("server.host", "SWAG_GEN_HOST")
	v.BindEnv("logger.level", "SWAG_GEN_LOG_LEVEL")

	// 解析配置
	var cfg Config
	if err := v.Unmarshal(&cfg); err != nil {
		return nil, fmt.Errorf("解析配置失败: %w", err)
	}

	return &cfg, nil
}

// setDefaults 设置默认值
func setDefaults(v *viper.Viper) {
	// 服务器配置
	v.SetDefault("server.host", "0.0.0.0")
	v.SetDefault("server.port", 8080)
	v.SetDefault("server.env", "development")
	v.SetDefault("server.read_timeout", 30)
	v.SetDefault("server.write_timeout", 30)

	// 项目配置
	v.SetDefault("project.name", "API Documentation")
	v.SetDefault("project.version", "1.0.0")
	v.SetDefault("project.description", "Generated by swag-gen")
	v.SetDefault("project.base_path", "/api/v1")

	// 解析器配置
	v.SetDefault("parser.enable_cache", true)
	v.SetDefault("parser.cache_ttl", 3600)
	v.SetDefault("parser.max_concurrent", 4)
	v.SetDefault("parser.exclude_dirs", []string{"vendor", "node_modules", ".git", "test", "tests"})

	// Swagger 配置
	v.SetDefault("swagger.version", "3.0.0")
	v.SetDefault("swagger.default_version", "1.0.0")
	v.SetDefault("swagger.default_title", "API Documentation")
	v.SetDefault("swagger.default_description", "Generated by swag-gen")

	// 日志配置
	v.SetDefault("logger.level", "info")
	v.SetDefault("logger.format", "json")
	v.SetDefault("logger.output", "stdout")
}

// Save 保存配置到文件
func (c *Config) Save(path string) error {
	// 确保目录存在
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("创建目录失败: %w", err)
	}

	// TODO: 实现配置保存逻辑
	return nil
}
