package config

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestLoad_WithDefaults(t *testing.T) {
	// 测试使用默认值加载配置
	cfg, err := Load("")
	require.NoError(t, err)
	assert.NotNil(t, cfg)

	// 验证默认值
	assert.Equal(t, "0.0.0.0", cfg.Server.Host)
	assert.Equal(t, 8080, cfg.Server.Port)
	assert.Equal(t, "development", cfg.Server.Env)
	assert.Equal(t, 30, cfg.Server.ReadTimeout)
	assert.Equal(t, 30, cfg.Server.WriteTimeout)

	assert.Equal(t, "API Documentation", cfg.Project.Name)
	assert.Equal(t, "1.0.0", cfg.Project.Version)
	assert.Equal(t, "Generated by swag-gen", cfg.Project.Description)
	assert.Equal(t, "/api/v1", cfg.Project.BasePath)

	assert.Equal(t, true, cfg.Parser.EnableCache)
	assert.Equal(t, 3600, cfg.Parser.CacheTTL)
	assert.Equal(t, 4, cfg.Parser.MaxConcurrent)
	assert.NotEmpty(t, cfg.Parser.ExcludeDirs)

	assert.Equal(t, "3.0.0", cfg.Swagger.Version)
	assert.Equal(t, "1.0.0", cfg.Swagger.DefaultVersion)
	assert.Equal(t, "API Documentation", cfg.Swagger.DefaultTitle)

	assert.Equal(t, "info", cfg.Logger.Level)
	assert.Equal(t, "json", cfg.Logger.Format)
	assert.Equal(t, "stdout", cfg.Logger.Output)
}

func TestLoad_WithConfigFile(t *testing.T) {
	// 创建临时配置文件
	tmpDir := t.TempDir()
	configPath := filepath.Join(tmpDir, "config.yaml")

	configContent := `
server:
  host: "127.0.0.1"
  port: 9090
  env: "production"
  read_timeout: 60
  write_timeout: 60

project:
  name: "Test API"
  version: "2.0.0"
  description: "Test Description"
  base_path: "/api/v2"

parser:
  enable_cache: false
  cache_ttl: 7200
  max_concurrent: 8
  exclude_dirs:
    - "vendor"
    - "test"

swagger:
  version: "3.1.0"
  default_version: "2.0.0"
  default_title: "Test API"
  default_description: "Test Description"

logger:
  level: "debug"
  format: "text"
  output: "stdout"
`

	err := os.WriteFile(configPath, []byte(configContent), 0644)
	require.NoError(t, err)

	// 加载配置
	cfg, err := Load(configPath)
	require.NoError(t, err)
	assert.NotNil(t, cfg)

	// 验证配置值
	assert.Equal(t, "127.0.0.1", cfg.Server.Host)
	assert.Equal(t, 9090, cfg.Server.Port)
	assert.Equal(t, "production", cfg.Server.Env)
	assert.Equal(t, 60, cfg.Server.ReadTimeout)
	assert.Equal(t, 60, cfg.Server.WriteTimeout)

	assert.Equal(t, "Test API", cfg.Project.Name)
	assert.Equal(t, "2.0.0", cfg.Project.Version)
	assert.Equal(t, "Test Description", cfg.Project.Description)
	assert.Equal(t, "/api/v2", cfg.Project.BasePath)

	assert.Equal(t, false, cfg.Parser.EnableCache)
	assert.Equal(t, 7200, cfg.Parser.CacheTTL)
	assert.Equal(t, 8, cfg.Parser.MaxConcurrent)

	assert.Equal(t, "3.1.0", cfg.Swagger.Version)
	assert.Equal(t, "2.0.0", cfg.Swagger.DefaultVersion)

	assert.Equal(t, "debug", cfg.Logger.Level)
	assert.Equal(t, "text", cfg.Logger.Format)
}

func TestLoad_WithEnvironmentVariables(t *testing.T) {
	// 设置环境变量
	os.Setenv("SWAG_GEN_PORT", "7070")
	os.Setenv("SWAG_GEN_HOST", "192.168.1.1")
	os.Setenv("SWAG_GEN_LOG_LEVEL", "warn")
	defer func() {
		os.Unsetenv("SWAG_GEN_PORT")
		os.Unsetenv("SWAG_GEN_HOST")
		os.Unsetenv("SWAG_GEN_LOG_LEVEL")
	}()

	// 加载配置
	cfg, err := Load("")
	require.NoError(t, err)
	assert.NotNil(t, cfg)

	// 验证环境变量覆盖
	assert.Equal(t, "192.168.1.1", cfg.Server.Host)
	assert.Equal(t, 7070, cfg.Server.Port)
	assert.Equal(t, "warn", cfg.Logger.Level)
}

func TestLoad_InvalidConfigFile(t *testing.T) {
	// 测试无效的配置文件路径
	cfg, err := Load("/nonexistent/path/config.yaml")
	// 应该返回错误
	assert.Error(t, err)
	assert.Nil(t, cfg)
}

func TestConfigSave(t *testing.T) {
	// 创建临时目录
	tmpDir := t.TempDir()
	savePath := filepath.Join(tmpDir, "subdir", "config.yaml")

	// 创建配置
	cfg := &Config{
		Server: ServerConfig{
			Host: "127.0.0.1",
			Port: 8080,
		},
		Project: ProjectConfig{
			Name:    "Test API",
			Version: "1.0.0",
		},
	}

	// 保存配置
	err := cfg.Save(savePath)
	require.NoError(t, err)

	// 验证文件是否存在
	_, err = os.Stat(filepath.Dir(savePath))
	assert.NoError(t, err)
}

func TestServerConfig_Defaults(t *testing.T) {
	cfg, err := Load("")
	require.NoError(t, err)

	// 验证服务器配置默认值
	assert.NotEmpty(t, cfg.Server.Host)
	assert.Greater(t, cfg.Server.Port, 0)
	assert.NotEmpty(t, cfg.Server.Env)
	assert.Greater(t, cfg.Server.ReadTimeout, 0)
	assert.Greater(t, cfg.Server.WriteTimeout, 0)
}

func TestProjectConfig_Defaults(t *testing.T) {
	cfg, err := Load("")
	require.NoError(t, err)

	// 验证项目配置默认值
	assert.NotEmpty(t, cfg.Project.Name)
	assert.NotEmpty(t, cfg.Project.Version)
	assert.NotEmpty(t, cfg.Project.BasePath)
}

func TestParserConfig_Defaults(t *testing.T) {
	cfg, err := Load("")
	require.NoError(t, err)

	// 验证解析器配置默认值
	assert.NotNil(t, cfg.Parser.EnableCache)
	assert.Greater(t, cfg.Parser.CacheTTL, 0)
	assert.Greater(t, cfg.Parser.MaxConcurrent, 0)
	assert.NotEmpty(t, cfg.Parser.ExcludeDirs)
}

func TestSwaggerConfig_Defaults(t *testing.T) {
	cfg, err := Load("")
	require.NoError(t, err)

	// 验证 Swagger 配置默认值
	assert.NotEmpty(t, cfg.Swagger.Version)
	assert.NotEmpty(t, cfg.Swagger.DefaultVersion)
	assert.NotEmpty(t, cfg.Swagger.DefaultTitle)
}

func TestLoggerConfig_Defaults(t *testing.T) {
	cfg, err := Load("")
	require.NoError(t, err)

	// 验证日志配置默认值
	assert.NotEmpty(t, cfg.Logger.Level)
	assert.NotEmpty(t, cfg.Logger.Format)
	assert.NotEmpty(t, cfg.Logger.Output)
}

func TestLoad_PartialConfigFile(t *testing.T) {
	// 创建只包含部分配置的文件
	tmpDir := t.TempDir()
	configPath := filepath.Join(tmpDir, "config.yaml")

	configContent := `
server:
  port: 9999
`

	err := os.WriteFile(configPath, []byte(configContent), 0644)
	require.NoError(t, err)

	// 加载配置
	cfg, err := Load(configPath)
	require.NoError(t, err)
	assert.NotNil(t, cfg)

	// 验证指定的值被覆盖
	assert.Equal(t, 9999, cfg.Server.Port)

	// 验证其他值使用默认值
	assert.Equal(t, "0.0.0.0", cfg.Server.Host)
	assert.Equal(t, "development", cfg.Server.Env)
}
